 
var leftMenuShtml = 
        "    <div class='menu'>                                                                                                                                                                                                                                                                  " +
        "                                                                                                                                                                                                                                                                             " +
        "        <!-- 判断菜单不是全部 全部为null -->                                                                                                                                                                                                                                 " +
        "                                                                                                                                                                                                                                                                             " +
        "        <div class='menu_item'>                                                                                                                                                                                                                                              " +
        "            <div class='menu_title' nid='89'>                                                                                                                                                                                                                                                        " +
        "                <h4><a href='Order_List.html?menuId=89&amp;menuParentId=1165&amp;myselfId=947' data-pid='89'><img src='Images/CgQSa1Y0TbKARlePAAAIAa_7lFg144.jpg' width='18' height='18' style='margin-top:-3px;'> 订单</a></h4>                                             " +
        "            </div>                                                                                                                                                                                                                                                           " +
        "        </div>                                                                                                                                                                                                                                                               " +
        "                                                                                                                                                                                                                                                                                   " +
        "        <div class='menu_item'>                                                                                                                                                                                                                                              " +
        "            <div class='menu_title' nid='71'>                                                                                                                                                                                                                                    " +
        "                <h4><a href='Market_CreateProduct.html?menuId=71&amp;menuParentId=125&amp;myselfId=2607' data-pid='71'><img src='Images/CgQSa1Y0Tc2AYHxNAAAHeVVyfuU503.jpg' width='18' height='18' style='margin-top:-3px;'> 营销</a></h4>                                   " +
        "            </div>                                                                                                                                                                                                                                                           " +
        "        </div>                                                                                                                                                                                                                                                                        " +
        "                                                                                                                                                                                                                                                                             " +
        "        <div class='menu_item'>                                                                                                                                                                                                                                              " +
        "            <div class='menu_title' nid='1565'>                                                                                                                                                                                                                                                    " +
        "                <h4><a href='Stock_OrderPickingList.html?menuId=1565&amp;menuParentId=1567&amp;myselfId=1441' data-pid='1565'><img src='Images/CgQSa1Y0TeCAO_CnAAAH-Nzsra4293.jpg' width='18' height='18' style='margin-top:-3px;'> 出库</a></h4>                            " +
        "            </div>                                                                                                                                                                                                                                                           " +
        "        </div>                                                                                                                                                                                                                                                               " +
        "                                                                                                                                                                                                                                                                             " +
        "        <div class='menu_item'>                                                                                                                                                                                                                                              " +
        "            <div class='menu_title' nid='1727'>                                                                                                                                                                                                                                             " +
        "                <h4><a href='Mobile_ShowSiteBasic.html?menuId=1727&amp;menuParentId=1806&amp;myselfId=1807' data-pid='1727'><img src='Images/CgQSa1Y0Te-ASCJXAAAFqFnSD6U572.jpg' width='18' height='18' style='margin-top:-3px;'> 移动版</a></h4>                            " +
        "            </div>                                                                                                                                                                                                                                                           " +
        "        </div>                                                                                                                                                                                                                                                               " +
        "                                                                                                                                                                                                                                                                             " +
        "                                                                                                                                                                                                                                                                             " +
        "        <div class='menu_item'>                                                                                                                                                                                                                                              " +
        "            <div class='menu_title' nid='1995'>                                                                                                                                                                                                                                                  " +
        "                <h4><a href='Shop_AuditList.html?menuId=1995&amp;menuParentId=1271&amp;myselfId=1273' data-pid='1995'><img src='Images/CgQSa1Y0TgCATN8tAAAKQ9fCiBk907.jpg' width='18' height='18' style='margin-top:-3px;'> 店铺</a></h4>                                    " +
        "            </div>                                                                                                                                                                                                                                                           " +
        "        </div>                                                                                                                                                                                                                                                               " +
        "                                                                                                                                                                                                                                                                             " +
        "                                                                                                                                                                                                                                                                             " +
        "        <div class='menu_item'>                                                                                                                                                                                                                                              " +
        "            <div class='menu_title' nid='1'>                                                                                                                                                                                                                                                        " +
        "                <h4><a href='System_BasicSetting.html?menuId=1&amp;menuParentId=37&amp;myselfId=38' data-pid='1'><img src='Images/default.png' width='18' height='18' style='margin-top:-3px;'> 系统</a></h4>                                                                " +
        "            </div>                                                                                                                                                                                                                                                           " +
        "        </div>                                                                                                                                                                                                                                                               " +
        "                                                                                                                                                                                                                                                                             " +
        "        <div class='menu_item'>                                                                                                                                                                                                                                              " +
        "            <div class='menu_title' nid='945'>                                                                                                                                                                                                                               " +
        "                <h4><a href='Site_TemplateSetting.html?menuId=945&amp;menuParentId=1039&amp;myselfId=1041' data-pid='945'><img src='Images/CgQSa1Y0ThaAKNKIAAAGh5zsM5E851.jpg' width='18' height='18' style='margin-top:-3px;'> 站点</a></h4>                                " +
        "            </div>                                                                                                                                                                                                                                                           " +
        "        </div>                                                                                                                                                                                                                                                               " +
        "                                                                                                                                                                                                                                                                             " +
        "        <div class='menu_item'>                                                                                                                                                                                                                                              " +
        "            <div class='menu_title' nid='3'>                                                                                                                                                                                                                                 " +
        "                <h4><a href='Product_Add.html?menuId=3&amp;menuParentId=7&amp;myselfId=1587' data-pid='3'><img src='Images/CgQSa1Y0Ti2AXSDaAAAIqXQn_ok941.jpg' width='18' height='18' style='margin-top:-3px;'> 商品</a></h4>                                                " +
        "            </div>                                                                                                                                                                                                                                                           " +
        "        </div>                                                                                                                                                                                                                                                               " +
        "        <div class='menu_item'>                                                                                                                                                                                                                                              " +
        "            <div class='menu_title' nid='4'>                                                                                                                                                                                                                                          " +
        "                <h4><a href='Member_List.html?menuId=4&amp;menuParentId=5&amp;myselfId=13' data-pid='4'><img src='Images/CgQSa1Y0TjuAEt1zAAAJJt_gnY8024.jpg' width='18' height='18' style='margin-top:-3px;'> 会员</a></h4>                                                  " +
        "            </div>                                                                                                                                                                                                                                                           " +
        "        </div>                                                                                                                                                                                                                                                               " +
        "                                                                                                                                                                                                                                                                             " +
        "        <div class='menu_item'>                                                                                                                                                                                                                                              " +
        "            <div class='menu_title' nid='1709'>                                                                                                                                                                                                                                    " +
        "                <h4><a href='Static_MemberIncreaseLevel.html?menuId=1709&amp;menuParentId=1959&amp;myselfId=1960' data-pid='1709'><img src='Images/CgQSa1Y0TkuAI2G8AAAE01Cxl28905.jpg' width='18' height='18' style='margin-top:-3px;'> 统计</a></h4>                        " +
        "            </div>                                                                                                                                                                                                                                                           " +
        "        </div>                                                                                                                                                                                                                                                               " +
        "                                                                                                                                                                                                                                                                             " +
        "        <div class='menu_item'>                                                                                                                                                                                                                                              " +
        "            <div class='menu_title' nid='4360'>                                                                                                                                                                                                                                      " +
        "                <h4><a class='selected' href='App_HomeTemplate.html' data-pid='4360'><img src='Images/default.png' width='18' height='18' style='margin-top:-3px;'> APP设置</a></h4>                                                                                         " +
        "            </div>                                                                                                                                                                                                                                                           " +
        "        </div>                                                                                                                                                                                                                                                               " +
        "    </div>                                                                                                                                                                                                                                                                   ";



$(document).ready(function () {
    $("#divLeftMenus").append(leftMenuShtml);
})