
var loginDialogShtml =
    "        <div id='feedback' class='modal fade Noprint' role='dialog'>                                                                             "+                              
    "        <div class='modal-dialog'>                                                                                                               "+
    "            <div class='modal-content'>                                                                                                          "+
    "                <div class='modal-header'>                                                                                                       "+
    "                    <button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>×</span></button>      "+
    "                    <h4 class='modal-title'>用户反馈</h4>                                                                                        "+
    "                </div>                                                                                                                           "+
    "                <div class='modal-body'>                                                                                                         "+
    "                    <form class='form-horizontal'>                                                                                               "+
    "                        <div class='form-group'>                                                                                                 "+
    "                            <label class='control-label col-sm-5'><span class='text-danger'>*</span>反馈内容：</label>                           "+
    "                            <div class='col-sm-1'></div>                                                                                         "+
    "                            <div class='col-sm-15'>                                                                                              "+
    "                                <textarea class='form-control' rows='5' id='feedbackcontent'></textarea>                                         "+
    "                            </div>                                                                                                               "+
    "                        </div>                                                                                                                   "+
    "                        <div class='form-group'>                                                                                                 "+
    "                            <label class='control-label col-sm-5'></label>                                                                       "+
    "                            <div class='col-sm-1'></div>                                                                                         "+
    "                            <div class='col-sm-10'>                                                                                              "+
    "                                <p class='text-muted'>限定输入250字</p>                                                                          "+
    "                            </div>                                                                                                               "+
    "                        </div>                                                                                                                   "+
    "                    </form>                                                                                                                      "+
    "                </div>                                                                                                                           "+
    "                <div class='modal-footer'>                                                                                                       "+
    "                    <button type='button' class='btn btn-primary' onclick='fankui();'>确定</button>                                              "+
    "                    <button type='button' class='btn btn-default' data-dismiss='modal'>取消</button>                                             "+
    "                </div>                                                                                                                           "+
    "            </div><!-- /.modal-content -->                                                                                                       "+
    "        </div><!-- /.modal-dialog -->                                                                                                            "+
    "    </div><!-- /.modal -->                                                                                                                       "+
    "                                                                                                                                                 "+
    "    <div id='goout' class='modal fade Noprint' role='dialog'>                                                                                    "+
    "        <div class='modal-dialog'>                                                                                                               "+
    "            <div class='modal-content'>                                                                                                          "+
    "                <div class='modal-header'>                                                                                                       "+
    "                    <button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>×</span></button>      "+
    "                    <h4 class='modal-title'>退出系统</h4>                                                                                        "+
    "                </div>                                                                                                                           "+
    "                <form class='form-horizontal' method='post' action='http://kstore.qianmi.com/boss/login.htm'>                                    "+
    "                    <div class='modal-body'>                                                                                                     "+
    "                        <div class='form-group'>                                                                                                 "+
    "                            <div class='col-sm-2'></div>                                                                                         "+
    "                            <div class='col-sm-7'>                                                                                               "+
    "                                <p class='text-muted'>您确定要退出系统吗？</p>                                                                   "+
    "                            </div>                                                                                                               "+
    "                        </div>                                                                                                                   "+
    "                                                                                                                                                 "+
    "                    </div>                                                                                                                       "+
    "                    <div class='modal-footer'>                                                                                                   "+
    "                        <input type='submit' class='btn btn-primary'>                                                                            "+
    "                        <button type='button' class='btn btn-default' data-dismiss='modal'>取消</button>                                         "+
    "                    </div>                                                                                                                       "+
    "                </form>                                                                                                                          "+
    "            </div><!-- /.modal-content -->                                                                                                       "+
    "        </div><!-- /.modal-dialog -->                                                                                                            "+
    "    </div><!-- /.modal -->                                                                                                                       "+

        "   <div id='dalog-send-sms' class='modal fade Noprint' role='dialog'>                                                                                                                                                                           " +
        "        <div class='modal-dialog'>                                                                                                                                                                                                              " +
        "            <div class='modal-content'>                                                                                                                                                                                                         " +
        "                <div class='modal-header'>                                                                                                                                                                                                      " +
        "                    <button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>×</span></button>                                                                                                     " +
        "                    <h4 class='modal-title'>密码验证</h4>                                                                                                                                                                                       " +
        "                </div>                                                                                                                                                                                                                          " +
        "                <div class='modal-body'>                                                                                                                                                                                                        " +
        "                    <form class='form-horizontal' id='sendCodeForm' method='post'>                                                                                                                                                              " +
        "                        <div class='form-group'>                                                                                                                                                                                                " +
        "                            <label class='control-label col-sm-5'>手机号码：</label>                                                                                                                                                            " +
        "                            <div class='col-sm-1'></div>                                                                                                                                                                                        " +
        "                            <div class='col-sm-5'>                                                                                                                                                                                              " +
        "                                <label class='radio-inline' style='padding-left:0px;'> <span id='viewmobile'></span></label>                                                                                                                    " +
        "                            </div>                                                                                                                                                                                                              " +
        "                            <div class='col-sm-1'></div>                                                                                                                                                                                        " +
        "                            <div class='col-sm-4'><input id='sendCodeButton' value='发送验证码' type='button' onclick='sendCode();'></div>                                                                                                      " +
        "                            <div class='col-sm-4'><label class='radio-inline'><span id='sendCodeButtonTip'></span></label></div>                                                                                                                " +
        "                        </div>                                                                                                                                                                                                                  " +
        "                                                                                                                                                                                                                                                " +
        "                        <div class='form-group'>                                                                                                                                                                                                " +
        "                            <label class='control-label col-sm-5'><span class='text-danger'>*</span>验证码：</label>                                                                                                                            " +
        "                            <div class='col-sm-1'></div>                                                                                                                                                                                        " +
        "                            <div class='col-sm-5'>                                                                                                                                                                                              " +
        "                                <input class='form-control required' rows='5' id='mcode'>                                                                                                                                                       " +
        "                                <span id='errorCode'></span>                                                                                                                                                                                    " +
        "                            </div>                                                                                                                                                                                                              " +
        "                        </div>                                                                                                                                                                                                                  " +
        "                                                                                                                                                                                                                                                " +
        "                                                                                                                                                                                                                                                " +
        "                    </form>                                                                                                                                                                                                                     " +
        "                </div>                                                                                                                                                                                                                          " +
        "                <div class='modal-footer'>                                                                                                                                                                                                      " +
        "                    <button type='button' class='btn btn-primary' onclick='checkCode();'>确定</button>                                                                                                                                          " +
        "                    <button type='button' class='btn btn-default' data-dismiss='modal'>取消</button>                                                                                                                                            " +
        "                </div>                                                                                                                                                                                                                          " +
        "            </div><!-- /.modal-content -->                                                                                                                                                                                                      " +
        "        </div><!-- /.modal-dialog -->                                                                                                                                                                                                           " +
        "    </div><!-- /.modal -->                                                                                                                                                                                                                      " +
        "                                                                                                                                                                                                                                                " +
        "                                                                                                                                                                                                                                                " +
        "    <div id='dalog-updatepass-sms' class='modal fade Noprint' role='dialog'>                                                                                                                                                                    " +
        "        <div class='modal-dialog'>                                                                                                                                                                                                              " +
        "            <div class='modal-content'>                                                                                                                                                                                                         " +
        "                <div class='modal-header'>                                                                                                                                                                                                      " +
        "                    <button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>×</span></button>                                                                                                     " +
        "                    <h4 class='modal-title'>修改密码</h4>                                                                                                                                                                                       " +
        "                </div>                                                                                                                                                                                                                          " +
        "                <div class='modal-body'>                                                                                                                                                                                                        " +
        "                    <form class='form-horizontal' method='post' id='updatePassForm'>                                                                                                                                                            " +
        "                        <div class='form-group'>                                                                                                                                                                                                " +
        "                            <label class='control-label col-sm-5'><span class='text-danger'>*</span>原始密码：</label>                                                                                                                          " +
        "                            <div class='col-sm-1'></div>                                                                                                                                                                                        " +
        "                            <div class='col-sm-10'>                                                                                                                                                                                             " +
        "                                <input class='form-control required' rows='5' name='userkey' id='userkey' type='password'><span id='oldpass'></span>                                                                                            " +
        "                            </div>                                                                                                                                                                                                              " +
        "                        </div>                                                                                                                                                                                                                  " +
        "                        <div class='form-group'>                                                                                                                                                                                                " +
        "                            <label class='control-label col-sm-5'><span class='text-danger'>*</span>新密码：</label>                                                                                                                            " +
        "                            <div class='col-sm-1'></div>                                                                                                                                                                                        " +
        "                            <div class='col-sm-10'>                                                                                                                                                                                             " +
        "                                <input class='form-control required' rows='5' name='newuserkey' id='newuserkey' type='password'>                                                                                                                " +
        "                            </div>                                                                                                                                                                                                              " +
        "                        </div>                                                                                                                                                                                                                  " +
        "                                                                                                                                                                                                                                                " +
        "                        <div class='form-group'>                                                                                                                                                                                                " +
        "                            <label class='control-label col-sm-5 required'><span class='text-danger'>*</span>重复新密码：</label>                                                                                                               " +
        "                            <div class='col-sm-1'></div>                                                                                                                                                                                        " +
        "                            <div class='col-sm-10'>                                                                                                                                                                                             " +
        "                                <input class='form-control' rows='5' equalto='#newuserkey' name='renewuserkey' id='renewuserkey' type='password'>                                                                                               " +
        "                            </div>                                                                                                                                                                                                              " +
        "                        </div>                                                                                                                                                                                                                  " +
        "                                                                                                                                                                                                                                                " +
        "                                                                                                                                                                                                                                                " +
        "                    </form>                                                                                                                                                                                                                     " +
        "                </div>                                                                                                                                                                                                                          " +
        "                <div class='modal-footer'>                                                                                                                                                                                                      " +
        "                    <button type='button' class='btn btn-primary' onclick='updatepass();'>确定</button>                                                                                                                                         " +
        "                    <button type='button' class='btn btn-default' data-dismiss='modal'>取消</button>                                                                                                                                            " +
        "                </div>                                                                                                                                                                                                                          " +
        "            </div><!-- /.modal-content -->                                                                                                                                                                                                      " +
        "        </div><!-- /.modal-dialog -->                                                                                                                                                                                                           " +
        "    </div><!-- /.modal -->                                                                                                                                                                                                                      " +
        "                                                                                                                                                                                                                                                " +
        "    <div id='dalog-checkPass-sms' class='modal fade Noprint' role='dialog'>                                                                                                                                                                     " +
        "        <div class='modal-dialog'>                                                                                                                                                                                                              " +
        "            <div class='modal-content'>                                                                                                                                                                                                         " +
        "                <div class='modal-header'>                                                                                                                                                                                                      " +
        "                    <button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>×</span></button>                                                                                                     " +
        "                    <h4 class='modal-title'>密码验证</h4>                                                                                                                                                                                       " +
        "                </div>                                                                                                                                                                                                                          " +
        "                <div class='modal-body'>                                                                                                                                                                                                        " +
        "                    <form class='form-horizontal' method='post' id='checkPassForm'>                                                                                                                                                             " +
        "                        <div class='form-group'>                                                                                                                                                                                                " +
        "                            <label class='control-label col-sm-5'><span class='text-danger'>*</span>原始密码：</label>                                                                                                                          " +
        "                            <div class='col-sm-1'></div>                                                                                                                                                                                        " +
        "                            <div class='col-sm-10'>                                                                                                                                                                                             " +
        "                                <input class='form-control required' rows='5' id='userkeyold' type='password'><span id='oldpassuse'></span>                                                                                                     " +
        "                            </div>                                                                                                                                                                                                              " +
        "                        </div>                                                                                                                                                                                                                  " +
        "                    </form>                                                                                                                                                                                                                     " +
        "                </div>                                                                                                                                                                                                                          " +
        "                <div class='modal-footer'>                                                                                                                                                                                                      " +
        "                    <button type='button' class='btn btn-primary' onclick='checkPass();'>确定</button>                                                                                                                                          " +
        "                    <button type='button' class='btn btn-default' data-dismiss='modal'>取消</button>                                                                                                                                            " +
        "                </div>                                                                                                                                                                                                                          " +
        "            </div><!-- /.modal-content -->                                                                                                                                                                                                      " +
        "        </div><!-- /.modal-dialog -->                                                                                                                                                                                                           " +
        "    </div><!-- /.modal -->                                                                                                                                                                                                                      " +
        "                                                                                                                                                                                                                                                " +
        "                                                                                                                                                                                                                                                " +
        "    <div id='dalog-Info-sms' class='modal fade Noprint' role='dialog' style='z-index:1700;'>                                                                                                                                                    " +
        "        <div class='modal-dialog' style='z-index:1800;'>                                                                                                                                                                                        " +
        "            <div class='modal-content'>                                                                                                                                                                                                         " +
        "                <div class='modal-header'>                                                                                                                                                                                                      " +
        "                    <button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>×</span></button>                                                                                                     " +
        "                    <h4 class='modal-title'>修改资料</h4>                                                                                                                                                                                       " +
        "                </div>                                                                                                                                                                                                                          " +
        "                <div class='modal-body'>                                                                                                                                                                                                        " +
        "                    <form class='form-horizontal' method='post' id='InfoForm' action='http://kstore.qianmi.com/boss/modifymanager.htm?CSRFToken=0b5606f8-27b2-4262-a34b-9dddc78d0b23' enctype='multipart/form-data'>                            " +
        "                        <div class='form-group'>                                                                                                                                                                                                " +
        "                            <label class='control-label col-sm-5'><span class='text-danger'>*</span>用户名：</label>                                                                                                                            " +
        "                            <div class='col-sm-1'></div>                                                                                                                                                                                        " +
        "                            <div class='col-sm-10'>                                                                                                                                                                                             " +
        "                                <input id='manaid' name='id' type='hidden' value='112'>                                                                                                                                                         " +
        "                                <label class='radio-inline'> <span class='usernamen'>qmbbc</span></label>                                                                                                                                       " +
        "                            </div>                                                                                                                                                                                                              " +
        "                        </div>                                                                                                                                                                                                                  " +
        "                        <div class='form-group'>                                                                                                                                                                                                " +
        "                            <label class='control-label col-sm-5'>头像：</label>                                                                                                                                                                " +
        "                            <div class='col-sm-1'></div>                                                                                                                                                                                        " +
        "                            <div class='col-sm-1'>                                                                                                                                                                                              " +
        "                                <input name='photoImg' id='photoImg1' type='hidden' value='http://183.131.78.28:10000/M00/00/20/CgQSa1X87z2AJygsAAEW0cU0BHY588.jpg'>                                                                            " +
        "                                <img src='Images/CgQSa1X87z2AJygsAAEW0cU0BHY588.jpg' height='30' id='headImgs'>                                                                                                                                 " +
        "                            </div>                                                                                                                                                                                                              " +
        "                            <div class='col-sm-1'></div>                                                                                                                                                                                        " +
        "                            <div class='col-sm-2'><input id='chooseAdminImg' type='button' value='选择'></div>                                                                                                                                  " +
        "                        </div>                                                                                                                                                                                                                  " +
        "                        <div class='form-group'>                                                                                                                                                                                                " +
        "                            <label class='control-label col-sm-5'>手机号：</label>                                                                                                                                                              " +
        "                            <div class='col-sm-1'></div>                                                                                                                                                                                        " +
        "                            <div class='col-sm-10'>                                                                                                                                                                                             " +
        "                                <input class='form-control mobile' rows='5' id='mobileupdate' name='mobile'>                                                                                                                                    " +
        "                            </div>                                                                                                                                                                                                              " +
        "                        </div>                                                                                                                                                                                                                  " +
        "                    </form>                                                                                                                                                                                                                     " +
        "                </div>                                                                                                                                                                                                                          " +
        "                <div class='modal-footer'>                                                                                                                                                                                                      " +
        "                    <button type='button' class='btn btn-primary' onclick='subInfoForm();'>确定</button>                                                                                                                                        " +
        "                    <button type='button' class='btn btn-default' data-dismiss='modal'>取消</button>                                                                                                                                            " +
        "                </div>                                                                                                                                                                                                                          " +
        "            </div><!-- /.modal-content -->                                                                                                                                                                                                      " +
        "        </div><!-- /.modal-dialog -->                                                                                                                                                                                                           " +
         "    </div><!-- /.modal -->    ";

$(document).ready(function(){
    $("#uLogin").append(loginDialogShtml);
    
});

